language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=1.24.1; BLAZEGRAPH=1.5.1
      php: 5.4
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DB=mysql; MW=1.19.20; TYPE=relbuild
    - env: DB=sqlite; MW=master@5cc1f1d; TYPE=composer
    - env: DB=sqlite; MW=master; PHPUNIT=4.6.*

install:
  - bash ./build/travis/install-services.sh
  - bash ./build/travis/install-mediawiki.sh
  - bash ./build/travis/install-semantic-mediawiki.sh

before_script:
  - bash ./build/travis/update-configuration-settings.sh

script:
  - bash ./build/travis/run-tests.sh

after_success:
  - bash ./build/travis/upload-coverage-report.sh
