language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=1.23.5; VIRTUOSO=7.2.2
      php: 5.4

  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DB=mysql; MW=1.25.2; TYPE=coverage
    - env: DB=mysql; MW=1.19.20; TYPE=relbuild
    - env: DB=sqlite; MW=1.25.2; TYPE=composer
    - env: DB=sqlite; MW=master; PHPUNIT=4.6.*
    - env: DB=mysql; MW=1.25.2; PHPUNIT=4.3.*; TYPE=benchmark
    - env: DB=mysql; MW=1.25.3; SESAME=2.7.14

# Travis support wrote (Tomcat + Java):
# bug in the JDK: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7089443.
# The hostname for the precise-gce platform is longer than 64 characters on the
# VM your job is running on
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

install:
  - travis_retry composer self-update
  - bash ./tests/travis/install-services.sh
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-mediawiki.sh

before_script:
  - bash ./tests/travis/update-configuration-settings.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
